flags: {}
packages:
- 'eclogues'
- 'eclogues-impl'
- location:
    git: git@github.com:rimmington/thrift-hs
    commit: 6fe95c60d5085723fc49ed8e156cae8dd151456f
  extra-dep: true
- location:
    git: git@github.com:rimmington/path-io
    commit: b5e6eeab41b77b435650425e7f8c1720ff27eaeb
  extra-dep: true
extra-deps:
- data-default-generics-0.3
- hzk-2.1.0
- servant-0.4.2
- servant-client-0.4.2
- servant-docs-0.4.2
- servant-pandoc-0.4.1.1
- servant-server-0.4.2
- stm-io-hooks-1.1.0
- utility-ht-0.0.10
- uuid-aeson-0.1.0.0
- wai-cors-0.2.2
- xdg-basedir-0.2.2
resolver: nightly-2015-07-23
